### ISSUE TITLE
Pycharm打印不出“厉”字

### ISSUE THREAD

**Issue by Regent0** [pingfangx/jetbrains-in-chinese#10]
本人用win10 64位，安装pycharm专业的最新版，下载汉化的最新版。print（"厉害"），只显示”害“字。其他字打印正常，没有乱码。尝试数次无果，在此求助。

**Comment by pingfangx** [comment]
你好，请删除汉化包，检查是否可以正常打印。
如果可以，可能是字体不兼容，请参照 [汉字乱码/中文显示为框框](https://github.com/pingfangx/TranslatorX/wiki#%E6%B1%89%E5%AD%97%E4%B9%B1%E7%A0%81%E4%B8%AD%E6%96%87%E6%98%BE%E7%A4%BA%E4%B8%BA%E6%A1%86%E6%A1%86) 的方法尝试使用其他字体。
