### ISSUE TITLE
好哥哥，再更新一下可以吗？

### ISSUE THREAD

**Issue by WuZhengqiang666** [pingfangx/jetbrains-in-chinese#23]
好哥哥，再更新一下可以吗？
2020年呐！

**Comment by hutaoseven** [comment]
下面是官方版汉化插件 适用 2020
[https://plugins.jetbrains.com/plugin/13710-chinese-simplified-language-pack-eap](https://plugins.jetbrains.com/plugin/13710-chinese-simplified-language-pack-eap)

**Comment by WuZhengqiang666** [comment]
谢谢，小哥哥。
帅气的小哥哥，七夕快乐！
