### ISSUE TITLE
可以为华为DevEco Studio做个汉化版的插件吗

### ISSUE THREAD

**Issue by 2535688890** [pingfangx/jetbrains-in-chinese#24]
可以为华为DevEco Studio做个汉化版的插件吗

**Comment by Estelle88** [comment]
抱歉，我不会写，你可以自己先百度看看中文版




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "pingfangx/jetbrains-in-chinese"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月23日(星期三) 晚上11:57
收件人:&nbsp;"pingfangx/jetbrains-in-chinese"<jetbrains-in-chinese@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[pingfangx/jetbrains-in-chinese] 可以为华为DevEco Studio做个汉化版的插件吗 (#24)





 
可以为华为DevEco Studio做个汉化版的插件吗

**Comment by yanyu323** [comment]
用IntelliJIDEA 2019.1的汉化包就可以完成菜单汉化。
感觉收到欺骗了。。。。所有的一切都是幻象。只不过是把别人的封装了一遍。怕被喷，不敢吐槽

**Comment by yanyu323** [comment]
用IntelliJIDEA 2019.1的汉化包可以汉化HUAWEI studio，是不是很开心？CTMD
