### ISSUE TITLE
Pycharm已经更新到2020.2.2版本了，跪求大佬更新

### ISSUE THREAD

**Issue by SunnyHong36** [pingfangx/jetbrains-in-chinese#25]
RT，现在想想更新到最新版什么配套的都没有，好后悔

**Comment by Aaily** [comment]
> RT现在想更新到最新版的什么配套都没有，好幻化

pycharm2020  官方有汉化包https://plugins.jetbrains.com/plugin/13710-chinese-simplified-language-pack----/versions
